// <auto-generated />
using System;
using MSA.Dal.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MSA.Dal.Migrations
{
    [DbContext(typeof(MSADbContext))]
    partial class MSADbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MSA.Entities.Entities.Product", b =>
                {
                    b.Property<int>("InProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("InProductId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<int>("InCount");

                    b.Property<string>("StCode")
                        .HasMaxLength(100);

                    b.Property<string>("StName")
                        .HasMaxLength(100);

                    b.HasKey("InProductId");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
